// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIwGEIiWnb03y5ayVsIuISPVgf58B5VLY',
    appId: '1:1011670601570:android:cfe0f5c1df89ab30d8a63b',
    messagingSenderId: '1011670601570',
    projectId: 'shopwave-e292f',
    storageBucket: 'shopwave-e292f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq5yYkmIE99o97LbgLJTUpXpdZfABOg9U',
    appId: '1:1011670601570:ios:3052784765efa470d8a63b',
    messagingSenderId: '1011670601570',
    projectId: 'shopwave-e292f',
    storageBucket: 'shopwave-e292f.firebasestorage.app',
    iosBundleId: 'com.example.shopwave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCATIJnHgxC2rw5tilp7Y-cJZ0cnz2sFoA',
    appId: '1:1011670601570:web:86e3e14bed3c588dd8a63b',
    messagingSenderId: '1011670601570',
    projectId: 'shopwave-e292f',
    authDomain: 'shopwave-e292f.firebaseapp.com',
    storageBucket: 'shopwave-e292f.firebasestorage.app',
    measurementId: 'G-BED0ZT5N1B',
  );
}
